### ISSUE TITLE
Cannot assign string to property of type ?int

### ISSUE THREAD

**Issue by loskov** [Jurager/exchange#1]
https://github.com/Jurager/exchange/blob/065d0da32081d2f55fa7fcd5f6e200fad7658f9b/src/Config.php#L57

https://github.com/Jurager/exchange/blob/065d0da32081d2f55fa7fcd5f6e200fad7658f9b/src/Config.php#L195

**Comment by Jurager** [comment]
Thanks! Fixed in 1.2
